### ISSUE TITLE
api-server pnpm typecheck/build fails: TS2352 in auth-impersonation.test.ts drizzle insert mock

### ISSUE THREAD

**Issue by shanemccaw** [shanemccaw/Shane-McCaw-MSP#3949]
## What's wrong

`artifacts/api-server` `pnpm run typecheck` (`tsc -p tsconfig.json --noEmit`) fails with one error, which also breaks `pnpm run build` (`build` = `typecheck && node ./build.mjs`):

```
src/routes/auth-impersonation.test.ts(53,24): error TS2352: Conversion of type 'Promise<never[]>' to type 'Promise<unknown[]> & { returning: (cols?: unknown) => Promise<unknown[]>; onConflictDoUpdate: (opts: unknown) => { returning: (cols?: unknown) => Promise<unknown[]>; }; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

## Root cause

The hand-rolled `db.insert().values()` mock (`auth-impersonation.test.ts:52-56`) casts `Promise.resolve([])` — inferred as `Promise<never[]>` — directly to an augmented `Promise<unknown[]> & { returning; onConflictDoUpdate }`. TS rejects the direct cast (insufficient overlap) and asks for a two-step `as unknown as …`. `tsconfig.json` has `include: ["src"]`, so test files are compiled by `typecheck`; the error is in-scope.

## Why it hasn't blocked the dev server

The dev-server coordinator rebuilds api-server via esbuild (`build.mjs`) directly, which does not typecheck — so the running :8080 server (and this build's own live verification) works despite the red typecheck. Any path that runs `pnpm run build` / `pnpm run typecheck` (CI, staging deploy gate) is broken.

## Fix

`const result = Promise.resolve([]) as unknown as Promise<unknown[]> & { … }` (the two-step cast TS suggests), or type the resolved value so the base overlaps.

## Evidence

- Reproduced on `origin/main` (~045923a) via `cd artifacts/api-server && npx tsc --noEmit` during the #3942 build.
- Not introduced by #3942 (that change only added a GET route to `auth.ts`; the error is in an untouched test file).

Discovered while building #3942 (GET /api/msp/auth/me).

**Comment by shanemccaw** [comment]
BUILD: model=claude-sonnet-5 effort=low buildSet=ApplicationCore
Posted: 2026-09-14T12:37:28Z

--model claude-sonnet-5 --effort low --title 3949

Fix the TS2352 double-cast error in auth-impersonation.test.ts's drizzle insert mock, breaking pnpm run typecheck/build. Real contract and the exact fix are in #3949's issue body — pull it in full before starting.

## Standing rules
- Pull #3949's full issue body AND all comments in order (later comments may supersede body)
- If you discover a genuine finding/bug mid-build: parent it as a direct sibling sub-issue of #1096 (EPIC: Application Core, no closer Feature-tier parent); label `bug` (+ `security` if relevant); prefix title `URGENT:` only if it can't wait
- Commit only your own changes on your own commit, push immediately after committing
- Per-issue bookend at build-journal/3949.md — IN FLIGHT first (own commit), DONE with real hash last (own commit)
- Timestamp on this dispatch and on bookend status lines ("Posted: <UTC ISO8601>")
- No fixture/hardcoded data

**Comment by shanemccaw** [comment]
Fixed. `artifacts/api-server/src/routes/auth-impersonation.test.ts:53` now uses the two-step `as unknown as Promise<unknown[]> & {...}` cast TS suggested, instead of the direct single cast that triggered TS2352.

Verified:
- `npx tsc -p tsconfig.json --noEmit` in `artifacts/api-server` — clean, no errors.
- `npm run build` (typecheck + esbuild) in `artifacts/api-server` — passes.

Commits (rebased onto `origin/main`, both merged):
- `b76aaf960` (rebased as `e9d44db0`) — the actual fix
- IN FLIGHT/DONE bookend commits in `build-journal/3949.md`

No new findings, no fixture data, no schema/backend changes needed for this fix.
