### ISSUE TITLE
BuildConsole ignores the new storeHealth field from provision-worktree --json (Git #1988) - a poisoned shared store is invisible at launch

### ISSUE THREAD

**Issue by shanemccaw** [shanemccaw/Shane-McCaw-MSP#2084]
Found during #1988. provision-worktree.mjs --json now returns a storeHealth object ({clean, foreign, dangling, poisonedBins}) - the provision-time scan of the shared main-checkout node_modules the new worktree junctions into. WorktreeProvisionService.RunProvisionAsync parses only ok/path/branch/reused/error (desktop/BuildConsole/Services/WorktreeProvisionService.cs:89-99), so a build launched against a poisoned store starts with no visible warning; the session then hits inexplicable tsc/vitest failures mid-build (the exact lost-session mode from #1955/#1967).

Surface it: parse storeHealth, and when clean=false log it to the worktree.provision ActivityLog channel and show a warning on the Build Watch slot at launch (message should point at 'node scripts/dev-server/store-doctor.mjs' and must not prescribe pnpm install, per #1987).

Evidence: scripts/dev-server/provision-worktree.mjs (storeHealth on both provision result paths, landed on main in 2e9a39594); desktop/BuildConsole/Services/WorktreeProvisionService.cs:89-99 parses no such field.

**Comment by shanemccaw** [comment]
BUILD: model=claude-sonnet-5 effort=medium buildSet=BuildConsole
Posted: 2026-09-06T15:18:54Z

--model claude-sonnet-5 --effort medium --title 2084

Fix per this issue's real confirmed gap. Read the full body — it names the exact real field (storeHealth) and the exact real file (WorktreeProvisionService.cs:89-99) that needs to parse and surface it. Real, direct relevance to pnpm store health, which Shane's been prioritizing tonight.

## Standing rules
- Pull #2084's full issue body AND all comments, in order — later comments may supersede body
- Commit only your own changes on your own commit, push immediately after committing
- Per-issue bookend at build-journal/2084.md — IN FLIGHT first (own commit), DONE with real hash last (own commit)
- Timestamp on this dispatch and on bookend status lines ("Posted: <UTC ISO8601>")
- No fixture/hardcoded data

**Comment by shanemccaw** [comment]
Done. Fixed the exact gap named in the issue: `WorktreeProvisionService.cs:89-99` parsed only `ok/path/branch/reused/error` from `provision-worktree.mjs --json`, silently dropping the real `storeHealth` object.

**What shipped** (commit `633781b81` on `main`; `c1c1d09ee` was the code commit before the bookend rebase):
- Added `StoreHealthInfo` / `StoreHealthAutoRepairInfo` to `WorktreeProvisionService.cs` and parse the real `storeHealth` JSON (`{clean, foreign, dangling, poisonedBins, autoRepair?, error?}`) on both provision result paths (reuse + fresh create).
- When unclean (or the scan itself errored), log a loud `worktree.provision` ActivityLog line naming `node scripts/dev-server/store-doctor.mjs` — never `pnpm install`, per #1987.
- Added `WorktreeProvisionService.PendingLaunchWarnings` (per-queue-item, since `QueueItem` is server-synced JSON with nowhere local to carry this) + `BuildStoreHealthWarning(...)`. `QueueWatcherService.LaunchItem` stashes the warning right after a successful provision; `BuildWatchWindow.OccupySlot` pops it and adds it as the first turn (styled as an error/warning paragraph) in that slot's transcript — a real visible warning on the Build Watch slot at launch, not just a log line.

**Verification:** `dotnet build` on `desktop/BuildConsole` — 0 warnings, 0 errors. Branch confirmed merged into `origin/main` via `scripts/dev-server/verify-branch-merged.mjs`. Working tree clean (`git status --porcelain`).

No fixture/hardcoded data — this only surfaces the real scan result the provisioner already computes.

Bookend: `build-journal/2084.md`.
