### ISSUE TITLE
ca-hold-window-scan.test.ts fails tsc --noEmit: ReportOnlyImpactSummary missing byCategory

### ISSUE THREAD

**Issue by shanemccaw** [shanemccaw/Shane-McCaw-MSP#4661]
## Evidence

Running \`pnpm --filter @workspace/api-server exec tsc --noEmit\` on current \`main\` (confirmed via a clean checkout, this session touched only \`artifacts/api-server/src/routes/public-chat.ts\` and its test file, unrelated to this) fails with 6 real errors, all in one file:

\`\`\`
src/lib/ca-hold-window-scan.test.ts(82,5): error TS2741: Property 'byCategory' is missing in type '{ signInsScanned: number; evaluated: number; wouldBlock: number; wouldInterrupt: number; wouldSatisfy: number; notApplied: number; affectedUserCount: number; affectedUsers: never[]; impactEvents: never[]; }' but required in type 'ReportOnlyImpactSummary'.
src/lib/ca-hold-window-scan.test.ts(100,7): error TS2741: (same)
src/lib/ca-hold-window-scan.test.ts(108,7): error TS2741: (same)
src/lib/ca-hold-window-scan.test.ts(115,7): error TS2741: (same)
src/lib/ca-hold-window-scan.test.ts(123,7): error TS2741: (same)
src/lib/ca-hold-window-scan.test.ts(153,7): error TS2741: (same)
[ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL] Command failed with exit code 2: tsc --noEmit
\`\`\`

\`artifacts/api-server/src/lib/ca-hold-window-scan.test.ts\` (Git #4550) builds \`CaPolicyImpact\` fixture objects with a \`summary\` field shaped like:

\`\`\`ts
summary: { signInsScanned: 10, evaluated: 5, wouldBlock: 0, wouldInterrupt: 0, wouldSatisfy: 5, notApplied: 0, affectedUserCount: 0, affectedUsers: [], impactEvents: [] }
\`\`\`

but \`ReportOnlyImpactSummary\` (referenced from \`ca-policy-promotion.ts\`) now requires a \`byCategory\` property this fixture never sets — a type drift between the test fixture and the real interface, introduced by whatever commit added \`byCategory\` to \`ReportOnlyImpactSummary\` without updating this test's fixture helper (\`impact()\`, around \`ca-hold-window-scan.test.ts\` line ~75).

\`git log --oneline -1 -- artifacts/api-server/src/lib/ca-hold-window-scan.test.ts\` shows the file's only commit is \`ebe904d4a #4550: write CA report-only impact to the customer hold-window verdict\` — so this has been broken since #4550 landed, not something recent.

## Impact

- \`tsc --noEmit\` on \`@workspace/api-server\` is not clean on \`main\` — this masks any *new* type error introduced elsewhere in the package, since the baseline is already red.
- \`vitest\` itself still runs and passes for this file at runtime (vitest doesn't type-check by default), so this was invisible to the normal test-run signal — only a real \`tsc --noEmit\` surfaces it.

## Fix

Add the missing \`byCategory\` field to the \`impact()\` fixture helper's default \`summary\` (and to each per-test override that redefines \`summary\`) in \`ca-hold-window-scan.test.ts\`, matching whatever shape \`ReportOnlyImpactSummary.byCategory\` actually requires in \`ca-policy-promotion.ts\`.

Found incidentally while verifying #4625 (deterministic public-chat form endpoint) via a full \`tsc --noEmit\` run — unrelated to that change, which touched only \`public-chat.ts\`/\`public-chat.test.ts\` and type-checks clean on its own.
